errors:
  something_went_wrong: SOMETHING_WENT_WRONG
  user:
    email_was_registered: EMAIL_WAS_REGISTERED
    email_not_registered: EMAIL_NOT_REGISTERED
    invalid_password: INVALID_PASSWORD
    not_authenticated: NOT_AUTHENTICATED
